export const rarityInfo = {
  common: { label: "凡品", weight: 64 },
  rare: { label: "灵品", weight: 26 },
  epic: { label: "玄品", weight: 9 },
  legendary: { label: "神品", weight: 1 },
};

export const styleInfo = {
  physical: { label: "物理", text: "直接伤害、连击、破防，成型后靠大数字爽杀。" },
  spell: { label: "法术", text: "雷法、灼烧、灵气联动；通过雷痕蓄力降下天劫，雷火烙印强化爆发。" },
  bleed: { label: "流血", text: "中期转为血魔流：自损换流血，再按敌人流血层数回血，成型后高爆发高回复。" },
  shell: { label: "龟壳", text: "通过格挡蓄势，再按当前格挡反震敌人；成型慢但稳，适合作为奖励流派。" },
  poison: { label: "中毒", text: "毒瘴会让敌人回合掉血，并按层数削弱敌人攻击；成型后靠虚弱拖垮强敌。" },
  control: { label: "控制" },
  guard: { label: "龟壳", text: "离间、禁锢和眩晕叠成心防崩裂，清空格挡并制造脆化爆发窗口。" },
};

export const gradeInfo = {
  1: "初阶",
  2: "中阶",
  3: "高阶",
};

export const statusInfo = {
  burn: { label: "灼烧", text: "回合间受到伤害，结算后消退一半。" },
  bleed: { label: "流血", text: "回合间和受到攻击时都会额外受伤，伤害先扣格挡，然后减少 1 层；血魔牌可按层数汲血回血。" },
  poison: { label: "毒瘴", text: "回合间受到伤害，然后减少 1 层；敌人攻击时，每 4 层毒瘴使其攻击 -1，最多 -5。" },
  curse: { label: "诅咒", text: "受到的卡牌伤害增加。" },
  spirit: { label: "灵气", text: "提高卡牌伤害，最多 12 层；低费牌只能承载部分灵气，战斗结束后清空。" },
  thunderMark: { label: "雷痕", text: "敌人身上的雷法层数。达到 8 层时触发天劫，造成 60 点无视格挡雷伤。" },
  stun: { label: "眩晕", text: "敌人行动前触发：跳过本次行动，然后减少 1 层。" },
  battleIntent: { label: "战意", text: "提高物理牌伤害；战意存在时，每打出一张物理伤害牌后继续增加战意。" },
  blockShield: { label: "格挡锁定", text: "格挡值不会被攻击消耗。回合结束时移除。" },
  spikes: { label: "荆棘", text: "受到攻击时反伤敌人。层数越高，反伤越强。" },
  controlResist: { label: "定力", text: "抵消即将施加的离间、禁锢、眩晕层数；每抵消 1 层消耗 1 层定力。敌人被控制影响行动后获得，正常行动后减少。" },
  thunderFireMark: { label: "雷火烙印", text: "由灼烧与雷痕共鸣形成。目标触发天劫时，每层雷火烙印使本次天劫额外造成 40 点无视格挡雷火伤害，然后消耗。" },
  clearMind: { label: "醒神", text: "下一次自身行动时，无视控制造成的行动跳过或转向。当前仅用于特殊机制。" },
  chaos: { label: "离间", text: "敌人行动前触发：攻击会优先打同伴，非攻击或没有同伴则空过，然后减少 1 层。" },
  bind: { label: "禁锢", text: "敌人行动前触发：攻击和施法会空过，格挡仍可执行，然后减少 1 层。" },
  brittle: { label: "脆化", text: "受到伤害变为 1.5 倍。离间、禁锢、眩晕中至少两类合计达到 6 层，或单类控制达到 8 层时触发心防崩裂，清空格挡并获得脆化。" },
  stasis: { label: "凝滞", text: "流血、毒瘴、离间将要减少层数时，先消耗凝滞并保留原状态。" },
  ward: { label: "护体", text: "抵消即将受到的伤害。" },
};

export const cards = {
  strike: {
    id: "strike",
    name: "斩妖式",
    rarity: "common",
    cost: 1,
    text: "造成 7 点伤害。",
    mythTags: ["人间"],
    style: "physical",
    grade: 1,
    effects: [{ type: "damage", target: "enemy", value: 7 }],
  },
  guard: {
    id: "guard",
    name: "护身咒",
    rarity: "common",
    cost: 1,
    text: "获得 6 点格挡。",
    mythTags: ["人间"],
    style: "shell",
    grade: 1,
    effects: [{ type: "block", target: "self", value: 6 }],
  },
  yellowCharm: {
    id: "yellowCharm",
    name: "黄符",
    rarity: "common",
    cost: 0,
    text: "造成 3 点伤害，抽 1 张牌。",
    mythTags: ["人间"],
    effects: [
      { type: "damage", target: "enemy", value: 3 },
      { type: "draw", value: 1 },
    ],
  },
  meditate: {
    id: "meditate",
    name: "调息",
    rarity: "common",
    cost: 0,
    text: "获得 1 点能量。能量已满时无法打出。",
    mythTags: ["昆仑"],
    effects: [{ type: "gainEnergy", value: 1 }],
  },
  breakArmor: {
    id: "breakArmor",
    name: "破甲符",
    rarity: "common",
    cost: 1,
    text: "造成 5 点伤害，施加 2 层诅咒。",
    mythTags: ["人间"],
    effects: [
      { type: "damage", target: "enemy", value: 5 },
      { type: "status", target: "enemy", status: "curse", stacks: 2 },
    ],
  },
  flameTalisman: { id: "flameTalisman", name: "火符", rarity: "common", cost: 1, text: "施加 12 层灼烧，获得 1 点灵气。", mythTags: ["天庭"], style: "spell", grade: 1, effects: [{ type: "status", target: "enemy", status: "burn", stacks: 12 },{ type: "status", target: "self", status: "spirit", stacks: 1 }]},
  foxFire: {
    id: "foxFire",
    name: "狐火",
    rarity: "rare",
    cost: 1,
    text: "造成 5 点伤害，施加 5 层灼烧和 4 层雷痕。",
    mythTags: ["妖", "天庭"],
    style: "spell",
    grade: 1,
    effects: [
      { type: "damage", target: "enemy", value: 5 },
      { type: "status", target: "enemy", status: "burn", stacks: 5 },
      { type: "thunderMark", target: "enemy", stacks: 4 },
    ],
  },
  ghostNeedle: {
    id: "ghostNeedle",
    name: "鬼针",
    rarity: "rare",
    cost: 1,
    text: "造成 4 点伤害，施加 5 层流血。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 1,
    effects: [
      { type: "damage", target: "enemy", value: 4 },
      { type: "status", target: "enemy", status: "bleed", stacks: 5 },
    ],
  },
  miasma: {
    id: "miasma",
    name: "毒瘴",
    rarity: "rare",
    cost: 1,
    text: "施加 10 层毒瘴。毒瘴会削弱敌人攻击。",
    mythTags: ["山海"],
    style: "poison",
    grade: 1,
    effects: [{ type: "status", target: "enemy", status: "poison", stacks: 10 }],
  },
  jiaoScale: {
    id: "jiaoScale",
    name: "蛟鳞",
    rarity: "rare",
    cost: 1,
    text: "获得 6 点格挡和 1 层护体。",
    mythTags: ["龙宫"],
    style: "shell",
    grade: 1,
    effects: [
      { type: "block", target: "self", value: 6 },
      { type: "status", target: "self", status: "ward", stacks: 1 },
    ],
  },
  demonMirror: {
    id: "demonMirror",
    name: "照妖镜",
    rarity: "epic",
    cost: 1,
    text: "获得 8 点格挡，施加 3 层诅咒。",
    mythTags: ["天庭"],
    style: "shell",
    grade: 2,
    effects: [
      { type: "block", target: "self", value: 8 },
      { type: "status", target: "enemy", status: "curse", stacks: 3 },
    ],
  },
  underworldPen: {
    id: "underworldPen",
    name: "幽冥判笔",
    rarity: "epic",
    cost: 2,
    text: "造成 10 点伤害，施加 6 层流血和 3 层诅咒。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 2,
    effects: [
      { type: "damage", target: "enemy", value: 10 },
      { type: "status", target: "enemy", status: "bleed", stacks: 6 },
      { type: "status", target: "enemy", status: "curse", stacks: 3 },
    ],
  },
    thornMail: { id: "thornMail", name: "荆棘甲", rarity: "common", cost: 1, text: "获得 6 点格挡和 2 层荆棘。", mythTags: ["山海"], style: "shell", grade: 1, effects: [{ type: "block", target: "self", value: 6 },{ type: "status", target: "self", status: "spikes", stacks: 2 }]},
  reflectArt: { id: "reflectArt", name: "反震诀", rarity: "rare", cost: 1, text: "获得 7 点格挡和 2 层荆棘。", mythTags: ["昆仑"], style: "shell", grade: 2, effects: [{ type: "block", target: "self", value: 7 },{ type: "status", target: "self", status: "spikes", stacks: 2 }]},
  turtleCrush: { id: "turtleCrush", name: "龟甲镇岳", rarity: "epic", cost: 2, text: "获得 12 点格挡和 3 层荆棘，并立即反射。", mythTags: ["山海"], style: "shell", grade: 3, effects: [{ type: "block", target: "self", value: 12 },{ type: "status", target: "self", status: "spikes", stacks: 3 },{ type: "spikeBurst", target: "allEnemies" }]},
  immovableVajra: { id: "immovableVajra", name: "不动明王身", rarity: "legendary", cost: 3, text: "获得 20 点格挡和 4 层荆棘，格挡翻倍。", mythTags: ["洪荒"], style: "shell", grade: 3, effects: [{ type: "block", target: "self", value: 20 },{ type: "status", target: "self", status: "spikes", stacks: 4 },{ type: "doubleBlock" }]},
  kunlunBreath: {
    id: "kunlunBreath",
    name: "昆仑吐纳",
    rarity: "epic",
    cost: 1,
    text: "获得 2 点灵气，抽 2 张牌。",
    mythTags: ["昆仑"],
    effects: [
      { type: "status", target: "self", status: "spirit", stacks: 2 },
      { type: "draw", value: 2 },
    ],
  },
  dragonRain: {
    id: "dragonRain",
    name: "龙宫雨",
    rarity: "epic",
    cost: 2,
    text: "对所有敌人造成 8 点伤害，施加 4 层灼烧。",
    mythTags: ["龙宫"],
    effects: [
      { type: "damage", target: "allEnemies", value: 8 },
      { type: "status", target: "allEnemies", status: "burn", stacks: 4 },
    ],
  },
  nuwaStone: {
    id: "nuwaStone",
    name: "女娲残石",
    rarity: "legendary",
    cost: 2,
    text: "回复 12 点生命，获得 3 点灵气。",
    mythTags: ["洪荒"],
    effects: [
      { type: "heal", target: "self", value: 12 },
      { type: "status", target: "self", status: "spirit", stacks: 3 },
    ],
  },
  eastBell: {
    id: "eastBell",
    name: "东皇钟影",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人造成 18 点伤害，获得 18 点格挡。",
    mythTags: ["洪荒"],
    style: "shell",
    grade: 3,
    effects: [
      { type: "damage", target: "allEnemies", value: 18 },
      { type: "block", target: "self", value: 18 },
    ],
  },
  panguMark: {
    id: "panguMark",
    name: "盘古斧痕",
    rarity: "legendary",
    cost: 2,
    text: "造成 30 点伤害。失去 6 点生命。",
    mythTags: ["洪荒"],
    effects: [
      { type: "damage", target: "enemy", value: 30 },
      { type: "loseHp", target: "self", value: 6 },
    ],
  },
  shanHaiCall: {
    id: "shanHaiCall",
    name: "山海唤形",
    rarity: "legendary",
    cost: 1,
    text: "抽 3 张牌，获得 2 点能量。",
    mythTags: ["山海"],
    effects: [
      { type: "draw", value: 3 },
      { type: "gainEnergy", value: 2 },
    ],
  },
  // V3.13N-C1A: compensate stoneShell revert — reflect 15%→17%
  shellTap: {
    id: "shellTap",
    name: "龟甲反震",
    rarity: "common",
    cost: 1,
    text: "获得 6 点格挡。对目标反震，造成当前格挡 17% 的伤害，不消耗格挡。",
    mythTags: ["山海"],
    style: "shell",
    grade: 1,
    effects: [
      { type: "block", target: "self", value: 6 },
      { type: "shellReflect", target: "enemy", ratio: 0.17, consumeRatio: 0 },
    ],
  },
  // V3.13N-C1A: revert to original 6 to reduce cross-style benefit
  stoneShell: {
    id: "stoneShell",
    name: "玄龟伏息",
    rarity: "rare",
    cost: 0,
    text: "获得 6 点格挡，抽 1 张牌。",
    mythTags: ["山海"],
    style: "shell",
    grade: 2,
    effects: [
      { type: "block", target: "self", value: 6 },
      { type: "draw", value: 1 },
    ],
  },
  // V3.13N-C1: buff shell rare AoE — reflect 10%→13%
  mountainEcho: {
    id: "mountainEcho",
    name: "负山回震",
    rarity: "rare",
    cost: 2,
    text: "获得 10 点格挡。对所有敌人反震，造成当前格挡 13% 的伤害，不消耗格挡。",
    mythTags: ["山海"],
    style: "shell",
    grade: 2,
    effects: [
      { type: "block", target: "self", value: 10 },
      { type: "shellReflect", target: "allEnemies", ratio: 0.13, consumeRatio: 0 },
    ],
  },
  xuanwuPrison: {
    id: "xuanwuPrison",
    name: "玄武镇狱",
    rarity: "epic",
    cost: 2,
    text: "获得 14 点格挡。对所有敌人反震，造成当前格挡 16% 的伤害，不消耗格挡。",
    mythTags: ["龙宫"],
    style: "shell",
    grade: 3,
    effects: [
      { type: "block", target: "self", value: 14 },
      { type: "shellReflect", target: "allEnemies", ratio: 0.16, consumeRatio: 0 },
    ],
  },
    armorBreaker: { id: "armorBreaker", name: "破甲斩", rarity: "rare", cost: 1, text: "造成 8 伤，低于50%翻倍。真武专属。", mythTags: ["人间"], style: "physical", grade: 2, trueMartial: true, effects: [{ type: "damage", target: "enemy", value: 8, tmExecute: true }]},
  killingIntent: { id: "killingIntent", name: "杀意决", rarity: "epic", cost: 2, text: "造成 16 伤，低于25%斩杀。真武专属。", mythTags: ["天庭"], style: "physical", grade: 3, trueMartial: true, effects: [{ type: "damage", target: "enemy", value: 16 },{ type: "execute", target: "enemy" }]},
  bloodSurge: { id: "bloodSurge", name: "血涌", rarity: "rare", cost: 1, text: "施加 8 层流血，消耗 2 生命。真武专属。", mythTags: ["幽冥"], style: "bleed", grade: 2, trueMartial: true, effects: [{ type: "status", target: "enemy", status: "bleed", stacks: 8 },{ type: "loseHp", target: "self", value: 2 }]},
  poisonBurst: { id: "poisonBurst", name: "毒爆", rarity: "rare", cost: 1, text: "立即触发毒瘴伤害不消耗，获得 6 点格挡。真武专属。", mythTags: ["山海"], style: "poison", grade: 2, trueMartial: true, effects: [{ type: "poisonBurst", target: "enemy" },{ type: "block", target: "self", value: 6 }]},
  boneDust: { id: "boneDust", name: "枯骨散", rarity: "epic", cost: 2, text: "施加 10 层毒瘴。真武专属。", mythTags: ["山海"], style: "poison", grade: 3, trueMartial: true, effects: [{ type: "status", target: "enemy", status: "poison", stacks: 10 }]},
  curseKill: { id: "curseKill", name: "咒杀术", rarity: "rare", cost: 1, text: "对被控敌人造成 25 伤。真武专属。", mythTags: ["幽冥"], style: "control", grade: 2, trueMartial: true, effects: [{ type: "damage", target: "enemy", value: 25 }]},
  bloodRecycle: { id: "bloodRecycle", name: "血魔回天", rarity: "epic", cost: 1, text: "按流血层数50%回复。真武专属。", mythTags: ["幽冥"], style: "bleed", grade: 3, trueMartial: true, effects: [{ type: "bleedSiphon" }]},
  thunderArmy: { id: "thunderArmy", name: "雷部天兵", rarity: "epic", cost: 2, text: "造成 10 伤，施加 4 层雷印。真武专属。", mythTags: ["天庭"], style: "spell", grade: 3, trueMartial: true, effects: [{ type: "damage", target: "enemy", value: 10 },{ type: "thunderMark", target: "enemy", value: 4 }]},
  furySlash: { id: "furySlash", name: "怒斩", rarity: "common", cost: 1, text: "造成 7 伤，获得 3 层战意。真武专属。", mythTags: ["人间"], style: "physical", grade: 1, trueMartial: true, effects: [{ type: "damage", target: "enemy", value: 7 },{ type: "status", target: "self", status: "battleIntent", stacks: 3 }]},
  thunderCall: { id: "thunderCall", name: "唤雷术", rarity: "common", cost: 1, text: "造成 5 伤，施加 3 层雷印。真武专属。", mythTags: ["天庭"], style: "spell", grade: 1, trueMartial: true, effects: [{ type: "damage", target: "enemy", value: 5 },{ type: "thunderMark", target: "enemy", value: 3 }]},
  bloodFang: { id: "bloodFang", name: "血牙", rarity: "common", cost: 1, text: "施加 5 层流血，回复 6 生命。真武专属。", mythTags: ["幽冥"], style: "bleed", grade: 1, trueMartial: true, effects: [{ type: "status", target: "enemy", status: "bleed", stacks: 5 },{ type: "heal", target: "self", value: 6 }]},
    warGodStrike: { id: "warGodStrike", name: "战神一击", rarity: "common", cost: 2, text: "造成 20 点伤害。真武专属。", mythTags: ["天庭"], style: "physical", grade: 1, trueMartial: true, effects: [{ type: "damage", target: "enemy", value: 20 }]},
  thunderBurst: { id: "thunderBurst", name: "雷爆", rarity: "common", cost: 1, text: "如果目标有3层以上雷印，立即触发天劫。真武专属。", mythTags: ["天庭"], style: "spell", grade: 1, trueMartial: true, effects: [{ type: "thunderMark", target: "enemy", value: 5 }]},
  venomFang: { id: "venomFang", name: "毒牙", rarity: "common", cost: 1, text: "施加 6 层毒瘴，获得 5 点格挡。真武专属。", mythTags: ["山海"], style: "poison", grade: 1, trueMartial: true, effects: [{ type: "status", target: "enemy", status: "poison", stacks: 6 },{ type: "block", target: "self", value: 5 }]},
  skyShellMandate: {
    id: "skyShellMandate",
    name: "天龟负碑",
    rarity: "legendary",
    cost: 3,
    text: "获得 16 点格挡。对所有敌人反震，造成当前格挡 20% 的伤害，不消耗格挡，抽 1 张牌。",
    mythTags: ["洪荒"],
    style: "shell",
    grade: 3,
    effects: [
      { type: "block", target: "self", value: 16 },
      { type: "shellReflect", target: "allEnemies", ratio: 0.20, consumeRatio: 0 },
      { type: "draw", value: 1 },
    ],
  },
  heavySlash: {
    id: "heavySlash",
    name: "重斩",
    rarity: "common",
    cost: 2,
    text: "造成 22 点伤害。",
    mythTags: ["人间"],
    style: "physical",
    grade: 1,
    effects: [{ type: "damage", target: "enemy", value: 22 }],
  },
  readyStance: {
    id: "readyStance",
    name: "开山架势",
    rarity: "common",
    cost: 0,
    text: "获得 6 层战意，抽 1 张牌。战意存在时，物理牌伤害 +战意；每打出一张物理伤害牌后战意 +7。",
    mythTags: ["人间"],
    style: "physical",
    grade: 1,
    effects: [
      { type: "status", target: "self", status: "battleIntent", stacks: 6 },
      { type: "draw", value: 1 },
    ],
  },
  chainBlade: {
    id: "chainBlade",
    name: "连环刃",
    rarity: "rare",
    cost: 1,
    text: "连续造成 8 点伤害两次。",
    mythTags: ["人间"],
    style: "physical",
    grade: 2,
    effects: [
      { type: "damage", target: "enemy", value: 8 },
      { type: "damage", target: "enemy", value: 8 },
    ],
  },
  battleCry: {
    id: "battleCry",
    name: "刑天战吼",
    rarity: "rare",
    cost: 0,
    text: "获得 8 层战意，抽 1 张牌。战意存在时，物理牌伤害 +战意；每打出一张物理伤害牌后战意 +7。",
    mythTags: ["洪荒"],
    style: "physical",
    grade: 2,
    effects: [
      { type: "status", target: "self", status: "battleIntent", stacks: 8 },
      { type: "draw", value: 1 },
    ],
  },
  armyBreaker: {
    id: "armyBreaker",
    name: "破军三式",
    rarity: "epic",
    cost: 2,
    text: "造成 20 点伤害两次，施加 4 层诅咒。",
    mythTags: ["天庭"],
    style: "physical",
    grade: 3,
    effects: [
      { type: "damage", target: "enemy", value: 20 },
      { type: "damage", target: "enemy", value: 20 },
      { type: "status", target: "enemy", status: "curse", stacks: 4 },
    ],
  },
  xingtianCleave: {
    id: "xingtianCleave",
    name: "刑天断首",
    rarity: "epic",
    cost: 3,
    text: "若目标生命不高于 45%，无视格挡斩杀；否则造成 36 点伤害。",
    mythTags: ["洪荒"],
    style: "physical",
    grade: 3,
    effects: [{ type: "execute", target: "enemy", threshold: 45, fallbackDamage: 36 }],
  },
  tiangangBreak: {
    id: "tiangangBreak",
    name: "天罡破阵",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人造成 36 点伤害，获得 20 点格挡。",
    mythTags: ["天庭"],
    style: "physical",
    grade: 3,
    effects: [
      { type: "damage", target: "allEnemies", value: 36 },
      { type: "block", target: "self", value: 20 },
    ],
  },
  thunderCharm: {
    id: "thunderCharm",
    name: "雷符",
    rarity: "common",
    cost: 1,
    text: "造成 8 点伤害，施加 6 层雷痕，获得 1 点灵气。",
    mythTags: ["天庭"],
    style: "spell",
    grade: 1,
    effects: [
      { type: "damage", target: "enemy", value: 8 },
      { type: "thunderMark", target: "enemy", stacks: 6 },
      { type: "status", target: "self", status: "spirit", stacks: 1 },
    ],
  },
  attractThunder: {
    id: "attractThunder",
    name: "引雷诀",
    rarity: "common",
    cost: 0,
    text: "施加 5 层雷痕，获得 1 点灵气。",
    mythTags: ["天庭"],
    style: "spell",
    grade: 1,
    effects: [
      { type: "thunderMark", target: "enemy", stacks: 5 },
      { type: "status", target: "self", status: "spirit", stacks: 1 },
    ],
  },
  fireRite: {
    id: "fireRite",
    name: "火德小祭",
    rarity: "rare",
    cost: 1,
    text: "对所有敌人造成 5 点伤害，施加 4 层灼烧。",
    mythTags: ["天庭"],
    style: "spell",
    grade: 2,
    effects: [
      { type: "damage", target: "allEnemies", value: 5 },
      { type: "status", target: "allEnemies", status: "burn", stacks: 4 },
    ],
  },
  fiveThunder: {
    id: "fiveThunder",
    name: "五雷正法",
    rarity: "epic",
    cost: 2,
    text: "造成 18 点伤害，施加 5 层雷痕，抽 1 张牌。",
    mythTags: ["天庭"],
    style: "spell",
    grade: 3,
    effects: [
      { type: "damage", target: "enemy", value: 18 },
      { type: "thunderMark", target: "enemy", stacks: 5 },
      { type: "draw", value: 1 },
    ],
  },
  thunderPool: {
    id: "thunderPool",
    name: "雷池法坛",
    rarity: "rare",
    cost: 1,
    text: "对所有敌人施加 4 层雷痕，获得 1 点灵气。",
    mythTags: ["天庭"],
    style: "spell",
    grade: 2,
    effects: [
      { type: "thunderMark", target: "allEnemies", stacks: 4 },
      { type: "status", target: "self", status: "spirit", stacks: 1 },
    ],
  },
  nineHeavenTribulation: {
    id: "nineHeavenTribulation",
    name: "九霄劫令",
    rarity: "epic",
    cost: 3,
    text: "施加 8 层雷痕，抽 1 张牌。雷痕满 8 层会触发天劫。",
    mythTags: ["天庭"],
    style: "spell",
    grade: 3,
    effects: [
      { type: "thunderMark", target: "enemy", stacks: 8 },
      { type: "draw", value: 1 },
    ],
  },
  starFall: {
    id: "starFall",
    name: "星落九野",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人造成 22 点伤害，施加 4 层诅咒和 6 层雷痕，抽 2 张牌。",
    mythTags: ["昆仑"],
    style: "spell",
    grade: 3,
    effects: [
      { type: "damage", target: "allEnemies", value: 22 },
      { type: "status", target: "allEnemies", status: "curse", stacks: 4 },
      { type: "thunderMark", target: "allEnemies", stacks: 6 },
      { type: "draw", value: 2 },
    ],
  },
  bloodNeedle: {
    id: "bloodNeedle",
    name: "血针",
    rarity: "common",
    cost: 1,
    text: "造成 4 点伤害，施加 5 层流血。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 1,
    effects: [
      { type: "damage", target: "enemy", value: 4 },
      { type: "status", target: "enemy", status: "bleed", stacks: 5 },
    ],
  },
  bloodNet: {
    id: "bloodNet",
    name: "血网",
    rarity: "rare",
    cost: 1,
    text: "对所有敌人施加 6 层流血。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 2,
    effects: [{ type: "status", target: "allEnemies", status: "bleed", stacks: 6 }],
  },
  bloodOath: {
    id: "bloodOath",
    name: "血魔小誓",
    rarity: "rare",
    cost: 1,
    text: "失去 3 点生命。施加 7 层流血，然后每 2 层目标流血回复 1 点生命，再造成 9 点伤害。目标原有 3 层流血起血量正收益。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 2,
    effects: [
      { type: "loseHp", target: "self", value: 3 },
      { type: "status", target: "enemy", status: "bleed", stacks: 7 },
      { type: "bleedSiphon", target: "enemy", ratio: 2 },
      { type: "damage", target: "enemy", value: 9 },
    ],
  },
  bloodRiver: {
    id: "bloodRiver",
    name: "血河倒卷",
    rarity: "epic",
    cost: 2,
    text: "造成 12 点伤害，施加 10 层流血和 3 层诅咒。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 3,
    effects: [
      { type: "damage", target: "enemy", value: 12 },
      { type: "status", target: "enemy", status: "bleed", stacks: 10 },
      { type: "status", target: "enemy", status: "curse", stacks: 3 },
    ],
  },
  bloodDemonLoop: {
    id: "bloodDemonLoop",
    name: "血魔回环",
    rarity: "rare",
    cost: 1,
    text: "失去 5 点生命。若目标已有流血，流血 +8；然后每 2 层目标流血回复 1 点生命，抽 1 张牌并获得 1 点能量。目标原有 5 层流血起可循环正收益。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 2,
    effects: [
      { type: "loseHp", target: "self", value: 5 },
      { type: "amplifyDebuffs", target: "enemy", statuses: ["bleed"], value: 8 },
      { type: "bleedSiphon", target: "enemy", ratio: 2 },
      { type: "draw", value: 1 },
      { type: "gainEnergy", value: 1 },
    ],
  },
  asuraBlood: {
    id: "asuraBlood",
    name: "阿修罗血誓",
    rarity: "legendary",
    cost: 2,
    text: "失去 8 点生命。对所有敌人施加 16 层流血；每 2 层敌方流血回复 1 点生命，再造成 14 点群体伤害。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 3,
    effects: [
      { type: "loseHp", target: "self", value: 8 },
      { type: "status", target: "allEnemies", status: "bleed", stacks: 16 },
      { type: "bleedSiphon", target: "allEnemies", ratio: 2 },
      { type: "damage", target: "allEnemies", value: 14 },
    ],
  },
  poisonPowder: {
    id: "poisonPowder",
    name: "毒粉",
    rarity: "common",
    cost: 1,
    text: "施加 9 层毒瘴。毒瘴会削弱敌人攻击。",
    mythTags: ["山海"],
    style: "poison",
    grade: 1,
    effects: [{ type: "status", target: "enemy", status: "poison", stacks: 9 }],
  },
  numbingThorn: {
    id: "numbingThorn",
    name: "麻骨针",
    rarity: "common",
    cost: 1,
    text: "造成 6 点伤害，施加 5 层毒瘴。",
    mythTags: ["山海"],
    style: "poison",
    grade: 1,
    effects: [
      { type: "damage", target: "enemy", value: 6 },
      { type: "status", target: "enemy", status: "poison", stacks: 5 },
    ],
  },
  centipedeJar: {
    id: "centipedeJar",
    name: "蜈蚣蛊坛",
    rarity: "rare",
    cost: 1,
    text: "造成 9 点伤害，施加 7 层毒瘴。",
    mythTags: ["山海"],
    style: "poison",
    grade: 2,
    effects: [
      { type: "damage", target: "enemy", value: 9 },
      { type: "status", target: "enemy", status: "poison", stacks: 7 },
    ],
  },
  softBoneSmoke: {
    id: "softBoneSmoke",
    name: "软骨烟",
    rarity: "rare",
    cost: 1,
    text: "对所有敌人施加 7 层毒瘴，获得 9 点格挡。",
    mythTags: ["山海"],
    style: "poison",
    grade: 2,
    effects: [
      { type: "status", target: "allEnemies", status: "poison", stacks: 7 },
      { type: "block", target: "self", value: 9 },
    ],
  },
  thousandVenom: {
    id: "thousandVenom",
    name: "千毒入梦",
    rarity: "epic",
    cost: 2,
    text: "对所有敌人施加 10 层毒瘴，抽 1 张牌。",
    mythTags: ["山海"],
    style: "poison",
    grade: 3,
    effects: [
      { type: "status", target: "allEnemies", status: "poison", stacks: 10 },
      { type: "draw", value: 1 },
    ],
  },
  boneMeltMiasma: {
    id: "boneMeltMiasma",
    name: "化骨瘴",
    rarity: "epic",
    cost: 2,
    text: "施加 8 层毒瘴；若目标已有毒瘴，额外 +8。抽 1 张牌。",
    mythTags: ["山海"],
    style: "poison",
    grade: 3,
    effects: [
      { type: "amplifyDebuffs", target: "enemy", statuses: ["poison"], value: 8 },
      { type: "status", target: "enemy", status: "poison", stacks: 8 },
      { type: "draw", value: 1 },
    ],
  },
  guKing: {
    id: "guKing",
    name: "万蛊王令",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人施加 15 层毒瘴和 3 层诅咒。",
    mythTags: ["山海"],
    style: "poison",
    grade: 3,
    effects: [
      { type: "status", target: "allEnemies", status: "poison", stacks: 15 },
      { type: "status", target: "allEnemies", status: "curse", stacks: 3 },
    ],
  },
  discordCharm: {
    id: "discordCharm",
    name: "离间符",
    rarity: "common",
    cost: 1,
    text: "施加 1 层离间。",
    mythTags: ["人间"],
    style: "control",
    grade: 1,
    effects: [{ type: "status", target: "enemy", status: "chaos", stacks: 1 }],
  },
  bindingRope: {
    id: "bindingRope",
    name: "缚妖索",
    rarity: "common",
    cost: 1,
    text: "造成 4 点伤害，施加 2 层禁锢。",
    mythTags: ["人间"],
    style: "control",
    grade: 1,
    effects: [
      { type: "damage", target: "enemy", value: 4 },
      { type: "status", target: "enemy", status: "bind", stacks: 2 },
    ],
  },
  echoBell: {
    id: "echoBell",
    name: "回心铃",
    rarity: "rare",
    cost: 1,
    text: "对所有敌人施加 2 层禁锢，获得 8 点格挡。",
    mythTags: ["昆仑"],
    style: "control",
    grade: 2,
    effects: [
      { type: "status", target: "allEnemies", status: "bind", stacks: 2 },
      { type: "block", target: "self", value: 8 },
    ],
    // UI2: trueMartial mode nerf — cost 2, bind 1, block 6
    trueMartial: {
      cost: 2,
      text: "对所有敌人施加 1 层禁锢，获得 6 点格挡。（真武调整）",
      effects: [
        { type: "status", target: "allEnemies", status: "bind", stacks: 1 },
        { type: "block", target: "self", value: 6 },
      ],
    },
  },
  mirrorMind: {
    id: "mirrorMind",
    name: "照心返影",
    rarity: "epic",
    cost: 2,
    text: "施加 1 层离间、2 层禁锢和 2 层诅咒，抽 1 张牌。",
    mythTags: ["天庭"],
    style: "control",
    grade: 3,
    effects: [
      { type: "status", target: "enemy", status: "chaos", stacks: 1 },
      { type: "status", target: "enemy", status: "bind", stacks: 2 },
      { type: "status", target: "enemy", status: "curse", stacks: 2 },
      { type: "draw", value: 1 },
    ],
  },
  heavenlyDiscord: {
    id: "heavenlyDiscord",
    name: "天诛离魂",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人施加 1 层离间、2 层禁锢和 4 层诅咒。",
    mythTags: ["天庭"],
    style: "control",
    grade: 3,
    effects: [
      { type: "status", target: "allEnemies", status: "chaos", stacks: 1 },
      { type: "status", target: "allEnemies", status: "bind", stacks: 2 },
      { type: "status", target: "allEnemies", status: "curse", stacks: 4 },
    ],
  },
  traceCutter: {
    id: "traceCutter",
    name: "追痕斩",
    rarity: "rare",
    cost: 1,
    text: "造成 13 点伤害。目标已有负面状态各增加 2 层。",
    mythTags: ["人间"],
    style: "physical",
    grade: 2,
    effects: [
      { type: "damage", target: "enemy", value: 13 },
      { type: "amplifyDebuffs", target: "enemy", value: 2 },
    ],
  },
  stasisCharm: {
    id: "stasisCharm",
    name: "锁脉符",
    rarity: "rare",
    cost: 1,
    text: "施加 2 层禁锢和 1 层凝滞。",
    mythTags: ["昆仑"],
    style: "control",
    grade: 2,
    effects: [
      { type: "status", target: "enemy", status: "bind", stacks: 2 },
      { type: "status", target: "enemy", status: "stasis", stacks: 1 },
    ],
  },
  bloodMonument: {
    id: "bloodMonument",
    name: "凝血成碑",
    rarity: "epic",
    cost: 2,
    text: "施加 3 层凝滞。若目标有流血，流血增加 8 层。",
    mythTags: ["幽冥"],
    style: "bleed",
    grade: 3,
    effects: [
      { type: "status", target: "enemy", status: "stasis", stacks: 3 },
      { type: "amplifyDebuffs", target: "enemy", statuses: ["bleed"], value: 8 },
    ],
  },
  venomIncense: {
    id: "venomIncense",
    name: "万毒温床",
    rarity: "epic",
    cost: 2,
    text: "施加 3 层凝滞。若目标有毒瘴，毒瘴增加 8 层。",
    mythTags: ["山海"],
    style: "poison",
    grade: 3,
    effects: [
      { type: "status", target: "enemy", status: "stasis", stacks: 3 },
      { type: "amplifyDebuffs", target: "enemy", statuses: ["poison"], value: 8 },
    ],
  },
  discordLoop: {
    id: "discordLoop",
    name: "离魂回环",
    rarity: "epic",
    cost: 2,
    text: "对所有敌人施加 1 层离间、2 层禁锢和 1 层凝滞。",
    mythTags: ["天庭"],
    style: "control",
    grade: 3,
    effects: [
      { type: "status", target: "allEnemies", status: "chaos", stacks: 1 },
      { type: "status", target: "allEnemies", status: "bind", stacks: 2 },
      { type: "status", target: "allEnemies", status: "stasis", stacks: 1 },
    ],
  },
  doomSutra: {
    id: "doomSutra",
    name: "劫数留形",
    rarity: "legendary",
    cost: 3,
    text: "对所有敌人施加 4 层凝滞，并使已有负面状态各增加 4 层。",
    mythTags: ["洪荒"],
    style: "spell",
    grade: 3,
    effects: [
      { type: "status", target: "allEnemies", status: "stasis", stacks: 4 },
      { type: "amplifyDebuffs", target: "allEnemies", value: 4 },
    ],
  },
  gatherAsh: {
    id: "gatherAsh",
    name: "拾遗诀",
    rarity: "common",
    cost: 0,
    text: "从弃牌堆选择 1 张非控制牌加入手牌。",
    mythTags: ["人间"],
    effects: [{ type: "recoverDiscard", value: 1, excludeStyles: ["control"] }],
  },
  returnTalisman: {
    id: "returnTalisman",
    name: "归藏符",
    rarity: "rare",
    cost: 1,
    text: "从弃牌堆选择 1 张非控制牌加入手牌，获得 1 点能量。",
    mythTags: ["昆仑"],
    style: "spell",
    grade: 2,
    effects: [
      { type: "gainEnergy", value: 1 },
      { type: "recoverDiscard", value: 1, excludeStyles: ["control"] },
    ],
  },
  cycleMandate: {
    id: "cycleMandate",
    name: "轮回敕令",
    rarity: "epic",
    cost: 2,
    text: "从弃牌堆选择 2 张牌加入手牌，抽 1 张牌。",
    mythTags: ["幽冥"],
    style: "control",
    grade: 3,
    effects: [
      { type: "draw", value: 1 },
      { type: "recoverDiscard", value: 2 },
    ],
  },
  hiddenArchive: {
    id: "hiddenArchive",
    name: "万象归藏",
    rarity: "legendary",
    cost: 3,
    text: "从弃牌堆选择 2 张牌加入手牌，获得 2 点灵气。",
    mythTags: ["洪荒"],
    style: "spell",
    grade: 3,
    effects: [
      { type: "status", target: "self", status: "spirit", stacks: 2 },
      { type: "recoverDiscard", value: 2 },
    ],
  },
  // ===== T2-A3: 真武双合流路线牌 (36 cards: 6 routes x 6 stages) =====
  // A. physical+spell 雷霆破军路线
  thunderBreakArmyBase: {
    id: "thunderBreakArmyBase", name: "雷引破军", rarity: "rare", cost: 1,
    text: "【真武双合流·入门】出刀带雷，物理攻击触发雷霆爆发。造成 10 点伤害，施加 4 层雷痕。",
    mythTags: ["天庭"], style: "physical", fusionTier: 2, fusionRoute: "physical+spell", fusionStage: "base", fusionStyles: ["physical", "spell"], fusionName: "雷霆破军路线", grade: 2, trueMartial: true,
    effects: [
      { type: "damage", target: "enemy", value: 10 },
      { type: "thunderMark", target: "enemy", value: 4 },
    ],
  },
  thunderBladeAwakening: {
    id: "thunderBladeAwakening", name: "雷刀初鸣", rarity: "rare", cost: 1,
    text: "【真武双合流·押注】雷刀初鸣，战意涌起。造成 12 点伤害，施加 5 层雷痕，获得 2 层战意。",
    mythTags: ["天庭"], style: "physical", fusionTier: 2, fusionRoute: "physical+spell", fusionStage: "commit", fusionStyles: ["physical", "spell"], fusionName: "雷霆破军路线", grade: 2, trueMartial: true,
    effects: [
      { type: "damage", target: "enemy", value: 12 },
      { type: "thunderMark", target: "enemy", value: 5 },
      { type: "status", target: "self", status: "battleIntent", stacks: 2 },
    ],
  },
  thunderBreakArmy: {
    id: "thunderBreakArmy", name: "雷霆破军", rarity: "epic", cost: 2,
    text: "【真武双合流·成型】雷霆破军，战意贯甲。造成 18 点伤害，施加 7 层雷痕，获得 4 层战意。",
    mythTags: ["天庭"], style: "physical", fusionTier: 2, fusionRoute: "physical+spell", fusionStage: "formed", fusionStyles: ["physical", "spell"], fusionName: "雷霆破军路线", grade: 3, trueMartial: true,
    effects: [
      { type: "damage", target: "enemy", value: 18 },
      { type: "thunderMark", target: "enemy", value: 7 },
      { type: "status", target: "self", status: "battleIntent", stacks: 4 },
    ],
  },
  thunderWarGodSlash: {
    id: "thunderWarGodSlash", name: "雷武神斩", rarity: "epic", cost: 2,
    text: "【真武双合流·胡牌】雷武神斩，扫阵回灵。对所有敌人造成 10 点伤害，施加 6 层雷痕，获得 1 点能量。",
    mythTags: ["天庭"], style: "spell", fusionTier: 2, fusionRoute: "physical+spell", fusionStage: "highrollA", fusionStyles: ["physical", "spell"], fusionName: "雷霆破军路线", grade: 3, trueMartial: true,
    effects: [
      { type: "damage", target: "allEnemies", value: 10 },
      { type: "thunderMark", target: "allEnemies", value: 6 },
      { type: "gainEnergy", target: "self", value: 1 },
    ],
  },
  breakArmyThunderMomentum: {
    id: "breakArmyThunderMomentum", name: "破军雷势", rarity: "rare", cost: 1,
    text: "【真武双合流·胡牌】破军雷势，战意雷引。对所有敌人施加 4 层雷痕，获得 5 层战意，抽 1 张牌。",
    mythTags: ["天庭"], style: "physical", fusionTier: 2, fusionRoute: "physical+spell", fusionStage: "highrollB", fusionStyles: ["physical", "spell"], fusionName: "雷霆破军路线", grade: 2, trueMartial: true,
    effects: [
      { type: "thunderMark", target: "allEnemies", value: 4 },
      { type: "status", target: "self", status: "battleIntent", stacks: 5 },
      { type: "draw", value: 1 },
    ],
  },
  thunderLordBreakArmy: {
    id: "thunderLordBreakArmy", name: "雷尊破军", rarity: "legendary", cost: 2,
    text: "【真武双合流·大成】雷尊破军，万雷归宗。对所有敌人造成 14 点伤害，施加 8 层雷痕，获得 6 层战意。",
    mythTags: ["天庭"], style: "spell", fusionTier: 2, fusionRoute: "physical+spell", fusionStage: "mastery", fusionStyles: ["physical", "spell"], fusionName: "雷霆破军路线", grade: 3, trueMartial: true,
    effects: [
      { type: "damage", target: "allEnemies", value: 14 },
      { type: "thunderMark", target: "allEnemies", value: 8 },
      { type: "status", target: "self", status: "battleIntent", stacks: 6 },
    ],
  },
  // B. spell+bleed 雷血天罚路线
  thunderBloodBase: {
    id: "thunderBloodBase", name: "雷血引", rarity: "rare", cost: 1,
    text: "【真武双合流·入门】雷痕牵动流血，天罚群伤。施加 4 层雷痕和 4 层流血。",
    mythTags: ["天庭"], style: "spell", fusionTier: 2, fusionRoute: "spell+bleed", fusionStage: "base", fusionStyles: ["spell", "bleed"], fusionName: "雷血天罚路线", grade: 2, trueMartial: true,
    effects: [
      { type: "thunderMark", target: "enemy", value: 4 },
      { type: "status", target: "enemy", status: "bleed", stacks: 4 },
    ],
  },
  thunderBloodPulse: {
    id: "thunderBloodPulse", name: "雷血涌", rarity: "rare", cost: 1,
    text: "【真武双合流·押注】雷血涌动，回生续命。施加 5 层雷痕和 5 层流血，回复 3 点生命。",
    mythTags: ["幽冥"], style: "bleed", fusionTier: 2, fusionRoute: "spell+bleed", fusionStage: "commit", fusionStyles: ["spell", "bleed"], fusionName: "雷血天罚路线", grade: 2, trueMartial: true,
    effects: [
      { type: "thunderMark", target: "enemy", value: 5 },
      { type: "status", target: "enemy", status: "bleed", stacks: 5 },
      { type: "heal", target: "self", value: 3 },
    ],
  },
  thunderBloodJudgement: {
    id: "thunderBloodJudgement", name: "雷血天罚", rarity: "epic", cost: 2,
    text: "【真武双合流·成型】雷血天罚，群伤齐下。对所有敌人施加 6 层雷痕和 6 层流血，造成 8 点伤害。",
    mythTags: ["天庭"], style: "spell", fusionTier: 2, fusionRoute: "spell+bleed", fusionStage: "formed", fusionStyles: ["spell", "bleed"], fusionName: "雷血天罚路线", grade: 3, trueMartial: true,
    effects: [
      { type: "thunderMark", target: "allEnemies", value: 6 },
      { type: "status", target: "allEnemies", status: "bleed", stacks: 6 },
      { type: "damage", target: "allEnemies", value: 8 },
    ],
  },
  thunderBloodExecution: {
    id: "thunderBloodExecution", name: "雷血诛邪", rarity: "epic", cost: 2,
    text: "【真武双合流·胡牌】雷血诛邪，血魄回魂。对所有敌人施加 7 层雷痕和 8 层流血，按流血 25% 汲血。",
    mythTags: ["幽冥"], style: "bleed", fusionTier: 2, fusionRoute: "spell+bleed", fusionStage: "highrollA", fusionStyles: ["spell", "bleed"], fusionName: "雷血天罚路线", grade: 3, trueMartial: true,
    effects: [
      { type: "thunderMark", target: "allEnemies", value: 7 },
      { type: "status", target: "allEnemies", status: "bleed", stacks: 8 },
      { type: "bleedSiphon", target: "allEnemies", ratio: 4 },
    ],
  },
  thunderBloodChain: {
    id: "thunderBloodChain", name: "雷血连诛", rarity: "rare", cost: 1,
    text: "【真武双合流·胡牌】雷血连诛，抽牌续势。对所有敌人施加 5 层流血和 5 层雷痕，抽 1 张牌。",
    mythTags: ["天庭"], style: "spell", fusionTier: 2, fusionRoute: "spell+bleed", fusionStage: "highrollB", fusionStyles: ["spell", "bleed"], fusionName: "雷血天罚路线", grade: 2, trueMartial: true,
    effects: [
      { type: "status", target: "allEnemies", status: "bleed", stacks: 5 },
      { type: "thunderMark", target: "allEnemies", value: 5 },
      { type: "draw", value: 1 },
    ],
  },
  thunderBloodSovereign: {
    id: "thunderBloodSovereign", name: "雷血真君", rarity: "legendary", cost: 2,
    text: "【真武双合流·大成】雷血真君，万血归雷。对所有敌人施加 8 层雷痕和 10 层流血，回复 6 点生命。",
    mythTags: ["幽冥"], style: "bleed", fusionTier: 2, fusionRoute: "spell+bleed", fusionStage: "mastery", fusionStyles: ["spell", "bleed"], fusionName: "雷血天罚路线", grade: 3, trueMartial: true,
    effects: [
      { type: "thunderMark", target: "allEnemies", value: 8 },
      { type: "status", target: "allEnemies", status: "bleed", stacks: 10 },
      { type: "heal", target: "self", value: 6 },
    ],
  },
  // C. bleed+poison 腐血毒潮路线
  rottenBloodBase: {
    id: "rottenBloodBase", name: "腐血引", rarity: "rare", cost: 1,
    text: "【真武双合流·入门】毒血互催，持续伤害和续航。施加 4 层流血和 4 层毒瘴。",
    mythTags: ["山海"], style: "bleed", fusionTier: 2, fusionRoute: "bleed+poison", fusionStage: "base", fusionStyles: ["bleed", "poison"], fusionName: "腐血毒潮路线", grade: 2, trueMartial: true,
    effects: [
      { type: "status", target: "enemy", status: "bleed", stacks: 4 },
      { type: "status", target: "enemy", status: "poison", stacks: 4 },
    ],
  },
  venomBloodPulse: {
    id: "venomBloodPulse", name: "毒血滋生", rarity: "rare", cost: 1,
    text: "【真武双合流·押注】毒血滋生，双毒并催。施加 5 层流血和 6 层毒瘴。",
    mythTags: ["山海"], style: "poison", fusionTier: 2, fusionRoute: "bleed+poison", fusionStage: "commit", fusionStyles: ["bleed", "poison"], fusionName: "腐血毒潮路线", grade: 2, trueMartial: true,
    effects: [
      { type: "status", target: "enemy", status: "bleed", stacks: 5 },
      { type: "status", target: "enemy", status: "poison", stacks: 6 },
    ],
  },
  rottenBloodVenomTide: {
    id: "rottenBloodVenomTide", name: "腐血毒潮", rarity: "epic", cost: 2,
    text: "【真武双合流·成型】腐血毒潮，血毒并催。对所有敌人施加 6 层流血和 8 层毒瘴，流血毒瘴各增加 3 层。",
    mythTags: ["山海"], style: "poison", fusionTier: 2, fusionRoute: "bleed+poison", fusionStage: "formed", fusionStyles: ["bleed", "poison"], fusionName: "腐血毒潮路线", grade: 3, trueMartial: true,
    effects: [
      { type: "status", target: "allEnemies", status: "bleed", stacks: 6 },
      { type: "status", target: "allEnemies", status: "poison", stacks: 8 },
      { type: "amplifyDebuffs", target: "allEnemies", statuses: ["bleed","poison"], value: 3 },
    ],
  },
  rottenVenomSiphon: {
    id: "rottenVenomSiphon", name: "腐血回魂", rarity: "epic", cost: 2,
    text: "【真武双合流·胡牌】腐血回魂，毒血换生机。对所有敌人施加 7 层流血和 9 层毒瘴，回复 6 点生命。",
    mythTags: ["山海"], style: "poison", fusionTier: 2, fusionRoute: "bleed+poison", fusionStage: "highrollA", fusionStyles: ["bleed", "poison"], fusionName: "腐血毒潮路线", grade: 3, trueMartial: true,
    effects: [
      { type: "status", target: "allEnemies", status: "bleed", stacks: 7 },
      { type: "status", target: "allEnemies", status: "poison", stacks: 9 },
      { type: "heal", target: "self", value: 6 },
    ],
  },
  bloodVenomBloom: {
    id: "bloodVenomBloom", name: "腐血盛放", rarity: "rare", cost: 1,
    text: "【真武双合流·胡牌】腐血盛放，毒血齐开。对所有敌人施加 6 层流血和 6 层毒瘴，抽 1 张牌。",
    mythTags: ["山海"], style: "bleed", fusionTier: 2, fusionRoute: "bleed+poison", fusionStage: "highrollB", fusionStyles: ["bleed", "poison"], fusionName: "腐血毒潮路线", grade: 2, trueMartial: true,
    effects: [
      { type: "status", target: "allEnemies", status: "bleed", stacks: 6 },
      { type: "status", target: "allEnemies", status: "poison", stacks: 6 },
      { type: "draw", value: 1 },
    ],
  },
  rottenBloodSovereign: {
    id: "rottenBloodSovereign", name: "腐血毒尊", rarity: "legendary", cost: 2,
    text: "【真武双合流·大成】腐血毒尊，万毒归血。对所有敌人施加 9 层流血和 12 层毒瘴，流血毒瘴各增加 4 层。",
    mythTags: ["山海"], style: "poison", fusionTier: 2, fusionRoute: "bleed+poison", fusionStage: "mastery", fusionStyles: ["bleed", "poison"], fusionName: "腐血毒潮路线", grade: 3, trueMartial: true,
    effects: [
      { type: "status", target: "allEnemies", status: "bleed", stacks: 9 },
      { type: "status", target: "allEnemies", status: "poison", stacks: 12 },
      { type: "amplifyDebuffs", target: "allEnemies", statuses: ["bleed","poison"], value: 4 },
    ],
  },
  // D. poison+control 蛊禁大阵路线
  guForbiddenBase: {
    id: "guForbiddenBase", name: "蛊禁引", rarity: "rare", cost: 1,
    text: "【真武双合流·入门】控制不是拖死，而是催发毒爆。施加 5 层毒瘴和 1 层禁锢。",
    mythTags: ["山海"], style: "poison", fusionTier: 2, fusionRoute: "poison+control", fusionStage: "base", fusionStyles: ["poison", "control"], fusionName: "蛊禁大阵路线", grade: 2, trueMartial: true,
    effects: [
      { type: "status", target: "enemy", status: "poison", stacks: 5 },
      { type: "status", target: "enemy", status: "bind", stacks: 1 },
    ],
  },
  guLockPulse: {
    id: "guLockPulse", name: "蛊锁生瘴", rarity: "rare", cost: 1,
    text: "【真武双合流·押注】蛊锁生瘴，毒禁并起。施加 6 层毒瘴和 1 层禁锢，抽 1 张牌。",
    mythTags: ["山海"], style: "control", fusionTier: 2, fusionRoute: "poison+control", fusionStage: "commit", fusionStyles: ["poison", "control"], fusionName: "蛊禁大阵路线", grade: 2, trueMartial: true,
    effects: [
      { type: "status", target: "enemy", status: "poison", stacks: 6 },
      { type: "status", target: "enemy", status: "bind", stacks: 1 },
      { type: "draw", value: 1 },
    ],
  },
  guForbiddenArray: {
    id: "guForbiddenArray", name: "蛊禁大阵", rarity: "epic", cost: 2,
    text: "【真武双合流·成型】蛊禁大阵，禁制催毒爆。对所有敌人施加 8 层毒瘴、2 层禁锢、1 层离间，引爆毒瘴。",
    mythTags: ["山海"], style: "poison", fusionTier: 2, fusionRoute: "poison+control", fusionStage: "formed", fusionStyles: ["poison", "control"], fusionName: "蛊禁大阵路线", grade: 3, trueMartial: true,
    effects: [
      { type: "status", target: "allEnemies", status: "poison", stacks: 8 },
      { type: "status", target: "allEnemies", status: "bind", stacks: 2 },
      { type: "status", target: "allEnemies", status: "chaos", stacks: 1 },
      { type: "poisonBurst", target: "allEnemies" },
    ],
  },
  guForbiddenDetonation: {
    id: "guForbiddenDetonation", name: "蛊禁毒爆", rarity: "epic", cost: 2,
    text: "【真武双合流·胡牌】蛊禁毒爆，禁阵催毒不拖长控。对所有敌人施加 10 层毒瘴，引爆毒瘴，抽 1 张牌。",
    mythTags: ["山海"], style: "control", fusionTier: 2, fusionRoute: "poison+control", fusionStage: "highrollA", fusionStyles: ["poison", "control"], fusionName: "蛊禁大阵路线", grade: 3, trueMartial: true,
    effects: [
      { type: "status", target: "allEnemies", status: "poison", stacks: 10 },
      { type: "poisonBurst", target: "allEnemies" },
      { type: "draw", value: 1 },
    ],
  },
  guPrisonCommand: {
    id: "guPrisonCommand", name: "蛊狱敕令", rarity: "rare", cost: 1,
    text: "【真武双合流·胡牌】蛊狱敕令，毒禁续势。对所有敌人施加 7 层毒瘴和 1 层禁锢，获得 1 点能量。",
    mythTags: ["山海"], style: "poison", fusionTier: 2, fusionRoute: "poison+control", fusionStage: "highrollB", fusionStyles: ["poison", "control"], fusionName: "蛊禁大阵路线", grade: 2, trueMartial: true,
    effects: [
      { type: "status", target: "allEnemies", status: "poison", stacks: 7 },
      { type: "status", target: "allEnemies", status: "bind", stacks: 1 },
      { type: "gainEnergy", target: "self", value: 1 },
    ],
  },
  guForbiddenSovereign: {
    id: "guForbiddenSovereign", name: "蛊禁天阵", rarity: "legendary", cost: 2,
    text: "【真武双合流·大成】蛊禁天阵，阵启万毒归元。对所有敌人施加 12 层毒瘴和 2 层禁锢，引爆毒瘴，回复 5 点生命。",
    mythTags: ["山海"], style: "control", fusionTier: 2, fusionRoute: "poison+control", fusionStage: "mastery", fusionStyles: ["poison", "control"], fusionName: "蛊禁大阵路线", grade: 3, trueMartial: true,
    effects: [
      { type: "status", target: "allEnemies", status: "poison", stacks: 12 },
      { type: "status", target: "allEnemies", status: "bind", stacks: 2 },
      { type: "poisonBurst", target: "allEnemies" },
      { type: "heal", target: "self", value: 5 },
    ],
  },
  // E. control+shell 镇狱玄龟路线
  prisonTurtleBase: {
    id: "prisonTurtleBase", name: "镇狱引", rarity: "rare", cost: 1,
    text: "【真武双合流·入门】镇压敌势，玄龟反震。获得 10 点格挡，施加 1 层禁锢。",
    mythTags: ["人间"], style: "shell", fusionTier: 2, fusionRoute: "control+shell", fusionStage: "base", fusionStyles: ["control", "shell"], fusionName: "镇狱玄龟路线", grade: 2, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 10 },
      { type: "status", target: "enemy", status: "bind", stacks: 1 },
    ],
  },
  turtleSealGuard: {
    id: "turtleSealGuard", name: "玄龟锁势", rarity: "rare", cost: 1,
    text: "【真武双合流·押注】玄龟锁势，镇敌固己。获得 12 点格挡，施加 1 层禁锢，抽 1 张牌。",
    mythTags: ["人间"], style: "control", fusionTier: 2, fusionRoute: "control+shell", fusionStage: "commit", fusionStyles: ["control", "shell"], fusionName: "镇狱玄龟路线", grade: 2, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 12 },
      { type: "status", target: "enemy", status: "bind", stacks: 1 },
      { type: "draw", value: 1 },
    ],
  },
  prisonXuanTurtle: {
    id: "prisonXuanTurtle", name: "镇狱玄龟", rarity: "epic", cost: 2,
    text: "【真武双合流·成型】镇狱玄龟，格挡反震合一。获得 18 点格挡，所有敌人眩晕 1 层和禁锢 2 层，反震 16%。",
    mythTags: ["人间"], style: "shell", fusionTier: 2, fusionRoute: "control+shell", fusionStage: "formed", fusionStyles: ["control", "shell"], fusionName: "镇狱玄龟路线", grade: 3, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 18 },
      { type: "status", target: "allEnemies", status: "stun", stacks: 1 },
      { type: "status", target: "allEnemies", status: "bind", stacks: 2 },
      { type: "shellReflect", target: "allEnemies", ratio: 0.16, consumeRatio: 0 },
    ],
  },
  prisonTurtleCounter: {
    id: "prisonTurtleCounter", name: "玄龟镇魔", rarity: "epic", cost: 2,
    text: "【真武双合流·胡牌】玄龟镇魔，反震压敌。获得 20 点格挡，反震 18%，施加 1 层禁锢。",
    mythTags: ["人间"], style: "shell", fusionTier: 2, fusionRoute: "control+shell", fusionStage: "highrollA", fusionStyles: ["control", "shell"], fusionName: "镇狱玄龟路线", grade: 3, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 20 },
      { type: "shellReflect", target: "allEnemies", ratio: 0.18, consumeRatio: 0 },
      { type: "status", target: "allEnemies", status: "bind", stacks: 1 },
    ],
  },
  prisonShellRebound: {
    id: "prisonShellRebound", name: "镇狱反震", rarity: "rare", cost: 1,
    text: "【真武双合流·胡牌】镇狱反震，格挡抽牌。获得 14 点格挡，反震 14%，抽 1 张牌。",
    mythTags: ["人间"], style: "shell", fusionTier: 2, fusionRoute: "control+shell", fusionStage: "highrollB", fusionStyles: ["control", "shell"], fusionName: "镇狱玄龟路线", grade: 2, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 14 },
      { type: "shellReflect", target: "allEnemies", ratio: 0.14, consumeRatio: 0 },
      { type: "draw", value: 1 },
    ],
  },
  prisonTurtleSovereign: {
    id: "prisonTurtleSovereign", name: "镇狱玄尊", rarity: "legendary", cost: 2,
    text: "【真武双合流·大成】镇狱玄尊，万狱归甲。获得 24 点格挡，反震 20%，施加 2 层禁锢。",
    mythTags: ["人间"], style: "shell", fusionTier: 2, fusionRoute: "control+shell", fusionStage: "mastery", fusionStyles: ["control", "shell"], fusionName: "镇狱玄龟路线", grade: 3, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 24 },
      { type: "shellReflect", target: "allEnemies", ratio: 0.20, consumeRatio: 0 },
      { type: "status", target: "allEnemies", status: "bind", stacks: 2 },
    ],
  },
  // F. physical+shell 玄甲破军路线
  xuanArmorBase: {
    id: "xuanArmorBase", name: "玄甲引", rarity: "rare", cost: 1,
    text: "【真武双合流·入门】甲越厚，刀越狠。获得 10 点格挡，造成 8 点伤害。",
    mythTags: ["人间"], style: "shell", fusionTier: 2, fusionRoute: "physical+shell", fusionStage: "base", fusionStyles: ["physical", "shell"], fusionName: "玄甲破军路线", grade: 2, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 10 },
      { type: "damage", target: "enemy", value: 8 },
    ],
  },
  armorBladeGuard: {
    id: "armorBladeGuard", name: "甲刃并起", rarity: "rare", cost: 1,
    text: "【真武双合流·押注】甲刃并起，攻防一体。获得 12 点格挡，造成 10 点伤害。",
    mythTags: ["人间"], style: "physical", fusionTier: 2, fusionRoute: "physical+shell", fusionStage: "commit", fusionStyles: ["physical", "shell"], fusionName: "玄甲破军路线", grade: 2, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 12 },
      { type: "damage", target: "enemy", value: 10 },
    ],
  },
  xuanArmorBreakArmy: {
    id: "xuanArmorBreakArmy", name: "玄甲破军", rarity: "epic", cost: 2,
    text: "【真武双合流·成型】玄甲破军，甲厚刀狠。获得 14 点格挡，造成 16 点伤害，反震 18%。",
    mythTags: ["人间"], style: "physical", fusionTier: 2, fusionRoute: "physical+shell", fusionStage: "formed", fusionStyles: ["physical", "shell"], fusionName: "玄甲破军路线", grade: 3, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 14 },
      { type: "damage", target: "enemy", value: 16 },
      { type: "shellReflect", target: "allEnemies", ratio: 0.18, consumeRatio: 0 },
    ],
  },
  xuanArmorGodBreak: {
    id: "xuanArmorGodBreak", name: "玄甲神破", rarity: "epic", cost: 2,
    text: "【真武双合流·胡牌】玄甲神破，刀势再起。获得 18 点格挡，造成 20 点伤害，获得 1 点能量。",
    mythTags: ["人间"], style: "physical", fusionTier: 2, fusionRoute: "physical+shell", fusionStage: "highrollA", fusionStyles: ["physical", "shell"], fusionName: "玄甲破军路线", grade: 3, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 18 },
      { type: "damage", target: "enemy", value: 20 },
      { type: "gainEnergy", target: "self", value: 1 },
    ],
  },
  xuanArmorWarMomentum: {
    id: "xuanArmorWarMomentum", name: "玄甲战势", rarity: "rare", cost: 1,
    text: "【真武双合流·胡牌】玄甲战势，战意蓄甲。获得 16 点格挡，获得 4 层战意，抽 1 张牌。",
    mythTags: ["人间"], style: "shell", fusionTier: 2, fusionRoute: "physical+shell", fusionStage: "highrollB", fusionStyles: ["physical", "shell"], fusionName: "玄甲破军路线", grade: 2, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 16 },
      { type: "status", target: "self", status: "battleIntent", stacks: 4 },
      { type: "draw", value: 1 },
    ],
  },
  xuanArmorSovereign: {
    id: "xuanArmorSovereign", name: "玄甲武尊", rarity: "legendary", cost: 2,
    text: "【真武双合流·大成】玄甲武尊，甲破万军。获得 22 点格挡，造成 24 点伤害，反震 18%。",
    mythTags: ["人间"], style: "physical", fusionTier: 2, fusionRoute: "physical+shell", fusionStage: "mastery", fusionStyles: ["physical", "shell"], fusionName: "玄甲破军路线", grade: 3, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 22 },
      { type: "damage", target: "enemy", value: 24 },
      { type: "shellReflect", target: "allEnemies", ratio: 0.18, consumeRatio: 0 },
    ],
  },
  // ===== T2-A3: 6 天尊契机牌 (Heavenly Trigger Cards) =====
  triggerThunderBloodBreakArmy: {
    id: "triggerThunderBloodBreakArmy", name: "破军血雷契", rarity: "legendary", cost: 0,
    text: "【天尊契机】若已大成「雷霆破军」或「雷血天罚」路线，选择后进化为【真武三合流：雷血破军】。",
    mythTags: ["天庭"], trueMartial: true, heavenlyTrigger: true, fusionTier: 3,
    triggerTripleCardId: "thunderBloodBreakArmy",
    triggerRoutes: ["physical+spell", "spell+bleed"],
    triggerStyles: ["physical", "spell", "bleed"],
    triggerName: "破军血雷契",
    effects: [],
  },
  triggerThreeCalamityTribulation: {
    id: "triggerThreeCalamityTribulation", name: "三灾劫契", rarity: "legendary", cost: 0,
    text: "【天尊契机】若已大成「雷血天罚」或「腐血毒潮」路线，选择后进化为【真武三合流：三灾雷血毒劫】。",
    mythTags: ["山海"], trueMartial: true, heavenlyTrigger: true, fusionTier: 3,
    triggerTripleCardId: "threeCalamityBloodVenomTribulation",
    triggerRoutes: ["spell+bleed", "bleed+poison"],
    triggerStyles: ["spell", "bleed", "poison"],
    triggerName: "三灾劫契",
    effects: [],
  },
  triggerRottenGuPrison: {
    id: "triggerRottenGuPrison", name: "腐蛊狱契", rarity: "legendary", cost: 0,
    text: "【天尊契机】若已大成「腐血毒潮」或「蛊禁大阵」路线，选择后进化为【真武三合流：腐血蛊狱】。",
    mythTags: ["山海"], trueMartial: true, heavenlyTrigger: true, fusionTier: 3,
    triggerTripleCardId: "rottenBloodGuPrison",
    triggerRoutes: ["bleed+poison", "poison+control"],
    triggerStyles: ["bleed", "poison", "control"],
    triggerName: "腐蛊狱契",
    effects: [],
  },
  triggerXuanGuPrison: {
    id: "triggerXuanGuPrison", name: "玄蛊狱契", rarity: "legendary", cost: 0,
    text: "【天尊契机】若已大成「蛊禁大阵」或「镇狱玄龟」路线，选择后进化为【真武三合流：玄蛊镇狱】。",
    mythTags: ["山海"], trueMartial: true, heavenlyTrigger: true, fusionTier: 3,
    triggerTripleCardId: "xuanGuPrisonSuppress",
    triggerRoutes: ["poison+control", "control+shell"],
    triggerStyles: ["poison", "control", "shell"],
    triggerName: "玄蛊狱契",
    effects: [],
  },
  triggerDemonSuppressArmor: {
    id: "triggerDemonSuppressArmor", name: "镇魔甲契", rarity: "legendary", cost: 0,
    text: "【天尊契机】若已大成「镇狱玄龟」或「玄甲破军」路线，选择后进化为【真武三合流：镇魔玄甲】。",
    mythTags: ["人间"], trueMartial: true, heavenlyTrigger: true, fusionTier: 3,
    triggerTripleCardId: "demonSuppressXuanArmor",
    triggerRoutes: ["control+shell", "physical+shell"],
    triggerStyles: ["physical", "control", "shell"],
    triggerName: "镇魔甲契",
    effects: [],
  },
  triggerXuanThunderArmy: {
    id: "triggerXuanThunderArmy", name: "玄雷军契", rarity: "legendary", cost: 0,
    text: "【天尊契机】若已大成「玄甲破军」或「雷霆破军」路线，选择后进化为【真武三合流：玄雷破军】。",
    mythTags: ["天庭"], trueMartial: true, heavenlyTrigger: true, fusionTier: 3,
    triggerTripleCardId: "xuanThunderBreakArmy",
    triggerRoutes: ["physical+shell", "physical+spell"],
    triggerStyles: ["physical", "spell", "shell"],
    triggerName: "玄雷军契",
    effects: [],
  },
  // ===== T2-A3: 6 张三合流终极牌 (Triple Fusion Ultimate Cards) =====
  thunderBloodBreakArmy: {
    id: "thunderBloodBreakArmy", name: "雷血破军", rarity: "legendary", cost: 2,
    text: "【真武三合流：雷血破军】出刀、雷霆、流血合一，单体爆发与群体压制兼备。造成 22 点伤害，全体施加 7 层雷痕和 7 层流血，抽 1 张牌。",
    mythTags: ["天庭"], style: "physical", fusionTier: 3, fusionStyles: ["physical", "spell", "bleed"], fusionName: "雷血破军", grade: 3, trueMartial: true,
    effects: [
      { type: "damage", target: "enemy", value: 22 },
      { type: "thunderMark", target: "allEnemies", value: 7 },
      { type: "status", target: "allEnemies", status: "bleed", stacks: 7 },
      { type: "draw", value: 1 },
    ],
  },
  threeCalamityBloodVenomTribulation: {
    id: "threeCalamityBloodVenomTribulation", name: "三灾雷血毒劫", rarity: "legendary", cost: 2,
    text: "【真武三合流：三灾雷血毒劫】雷、血、毒三灾共鸣，持续伤害爆炸。全体施加 6 层雷痕、7 层流血、8 层毒瘴，流血毒瘴雷痕各增加 3 层。",
    mythTags: ["山海"], style: "spell", fusionTier: 3, fusionStyles: ["spell", "bleed", "poison"], fusionName: "三灾雷血毒劫", grade: 3, trueMartial: true,
    effects: [
      { type: "thunderMark", target: "allEnemies", value: 6 },
      { type: "status", target: "allEnemies", status: "bleed", stacks: 7 },
      { type: "status", target: "allEnemies", status: "poison", stacks: 8 },
      { type: "amplifyDebuffs", target: "allEnemies", statuses: ["bleed","poison","thunderMark"], value: 3 },
    ],
  },
  rottenBloodGuPrison: {
    id: "rottenBloodGuPrison", name: "腐血蛊狱", rarity: "legendary", cost: 2,
    text: "【真武三合流：腐血蛊狱】流血、毒、禁制连锁，控制转毒爆。全体施加 6 层流血、10 层毒瘴、2 层禁锢，引爆毒瘴，回复 5 点生命。",
    mythTags: ["山海"], style: "poison", fusionTier: 3, fusionStyles: ["bleed", "poison", "control"], fusionName: "腐血蛊狱", grade: 3, trueMartial: true,
    effects: [
      { type: "status", target: "allEnemies", status: "bleed", stacks: 6 },
      { type: "status", target: "allEnemies", status: "poison", stacks: 10 },
      { type: "status", target: "allEnemies", status: "bind", stacks: 2 },
      { type: "poisonBurst", target: "allEnemies" },
      { type: "heal", target: "self", value: 5 },
    ],
  },
  xuanGuPrisonSuppress: {
    id: "xuanGuPrisonSuppress", name: "玄蛊镇狱", rarity: "legendary", cost: 2,
    text: "【真武三合流：玄蛊镇狱】毒壳镇狱，敌人越拖越崩。获得 20 点格挡，全体施加 9 层毒瘴和 2 层禁锢，反震 18%。",
    mythTags: ["山海"], style: "shell", fusionTier: 3, fusionStyles: ["poison", "control", "shell"], fusionName: "玄蛊镇狱", grade: 3, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 20 },
      { type: "status", target: "allEnemies", status: "poison", stacks: 9 },
      { type: "status", target: "allEnemies", status: "bind", stacks: 2 },
      { type: "shellReflect", target: "allEnemies", ratio: 0.18, consumeRatio: 0 },
    ],
  },
  demonSuppressXuanArmor: {
    id: "demonSuppressXuanArmor", name: "镇魔玄甲", rarity: "legendary", cost: 2,
    text: "【真武三合流：镇魔玄甲】镇压、格挡、破军合一，控后重斩。获得 18 点格挡，全体施加 2 层禁锢，造成 22 点伤害，生命低于 35% 斩杀否则追加 8 点伤害。",
    mythTags: ["人间"], style: "physical", fusionTier: 3, fusionStyles: ["physical", "control", "shell"], fusionName: "镇魔玄甲", grade: 3, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 18 },
      { type: "status", target: "allEnemies", status: "bind", stacks: 2 },
      { type: "damage", target: "enemy", value: 22 },
      { type: "execute", target: "enemy", threshold: 35, fallbackDamage: 8 },
    ],
  },
  xuanThunderBreakArmy: {
    id: "xuanThunderBreakArmy", name: "玄雷破军", rarity: "legendary", cost: 2,
    text: "【真武三合流：玄雷破军】玄甲、破军、雷霆合一，攻防一体。获得 18 点格挡，全体造成 12 点伤害和 7 层雷痕，反震 16%。",
    mythTags: ["天庭"], style: "spell", fusionTier: 3, fusionStyles: ["physical", "spell", "shell"], fusionName: "玄雷破军", grade: 3, trueMartial: true,
    effects: [
      { type: "block", target: "self", value: 18 },
      { type: "damage", target: "allEnemies", value: 12 },
      { type: "thunderMark", target: "allEnemies", value: 7 },
      { type: "shellReflect", target: "allEnemies", ratio: 0.16, consumeRatio: 0 },
    ],
  },
  // 业障牌 — 不可通过普通删牌剔除，不进入普通奖励池
  karmaCurse: {
    id: "karmaCurse",
    name: "业障",
    rarity: "common",
    cost: 0,
    text: "抽到时滞塞手牌。不可通过普通删牌剔除。",
    mythTags: ["幽冥"],
    undeletable: true,
    isCurse: true,
    effects: [],
  },
};

export const enemies = {
  littleYao: {
    id: "littleYao",
    name: "小妖",
    maxHp: 22,
    intents: [{ type: "attack", value: 5, text: "扑咬 5" }],
  },
  shanxiao: {
    id: "shanxiao",
    name: "山魈",
    maxHp: 34,
    intents: [
      { type: "attack", value: 8, text: "挥爪 8" },
      { type: "block", value: 6, text: "缩身 6" },
    ],
  },
  foxYao: {
    id: "foxYao",
    name: "狐妖",
    maxHp: 28,
    intents: [
      { type: "attack", value: 4, text: "狐爪 4" },
      { type: "status", status: "burn", stacks: 3, text: "狐火 3" },
    ],
  },
  waterGhost: {
    id: "waterGhost",
    name: "水鬼",
    maxHp: 30,
    intents: [
      { type: "attack", value: 6, text: "拖拽 6" },
      { type: "status", status: "curse", stacks: 2, text: "怨念 2" },
    ],
  },
  ironCorpse: {
    id: "ironCorpse",
    name: "铁尸",
    maxHp: 45,
    intents: [
      { type: "attack", value: 10, text: "重击 10" },
      { type: "block", value: 10, text: "铁骨 10" },
    ],
  },
    yaoJiang: { id: "yaoJiang", name: "妖将", maxHp: 42, intents: [{ type: "attack", value: 8, text: "劈斩 8" },{ type: "attack", value: 12, text: "重劈 12" },{ type: "block", value: 8, text: "妖气护体 8" }]},
  shanJun: { id: "shanJun", name: "山君", maxHp: 80, intents: [{ type: "attack", value: 12, text: "虎爪 12" },{ type: "attack", value: 18, text: "扑杀 18" },{ type: "block", value: 12, text: "虎踞 12" },{ type: "status", status: "curse", stacks: 2, text: "虎啸震慑 2" }]},
  guiJiang: { id: "guiJiang", name: "鬼将", maxHp: 60, intents: [{ type: "attack", value: 10, text: "鬼爪 10" },{ type: "attack", value: 15, text: "索命 15" },{ type: "status", status: "curse", stacks: 3, text: "鬼咒 3" }]},
  panGuan: { id: "panGuan", name: "判官", maxHp: 120, intents: [{ type: "attack", value: 14, text: "判笔 14" },{ type: "attack", value: 20, text: "生死判 20" },{ type: "block", value: 15, text: "阴律护身 15" },{ type: "status", status: "curse", stacks: 4, text: "判词 4" }]},
  moZun: { id: "moZun", name: "魔尊", maxHp: 90, intents: [{ type: "attack", value: 14, text: "魔焰 14" },{ type: "attack", value: 20, text: "灭世 20" },{ type: "status", status: "burn", stacks: 4, text: "焚天 4" },{ type: "status", status: "curse", stacks: 3, text: "魔咒 3" }]},
  blackMountain: {
    id: "blackMountain",
    name: "黑山老妖",
    maxHp: 160,
    intents: [
      { type: "attack", value: 12, text: "压顶 12" },
      { type: "attack", value: 18, text: "裂山 18" },
      { type: "block", value: 16, text: "妖雾护身 16" },
      { type: "status", status: "curse", stacks: 3, text: "黑山咒 3" },
    ],
  },
};

// 真武模式独立敌人池
export const trueMartialEnemies = {
  // 试锋阶段 (1-5)
  bloodShade: {
    id: "bloodShade",
    name: "血影",
    maxHp: 28,
    intents: [
      { type: "attack", value: 7, text: "掠魂 7" },
      { type: "status", status: "bleed", stacks: 2, text: "血蚀 2" },
    ],
  },
  thunderWisp: {
    id: "thunderWisp",
    name: "雷精",
    maxHp: 24,
    intents: [
      { type: "attack", value: 6, text: "雷光 6" },
      { type: "status", status: "burn", stacks: 2, text: "灼闪 2" },
    ],
  },
  // 破阵阶段 (6-10)
  deathSentry: {
    id: "deathSentry",
    name: "死兆戍卫",
    maxHp: 52,
    intents: [
      { type: "attack", value: 11, text: "冥刺 11" },
      { type: "block", value: 10, text: "阴壁 10" },
      { type: "status", status: "curse", stacks: 1, text: "死咒 1" },
    ],
  },
  lavaWorm: {
    id: "lavaWorm",
    name: "熔岩蠕虫",
    maxHp: 48,
    intents: [
      { type: "attack", value: 9, text: "岩浆喷溅 9" },
      { type: "status", status: "burn", stacks: 3, text: "焚身 3" },
    ],
  },
  venomSerpent: {
    id: "venomSerpent",
    name: "毒蟒",
    maxHp: 44,
    intents: [
      { type: "attack", value: 8, text: "毒咬 8" },
      { type: "status", status: "poison", stacks: 3, text: "剧毒 3" },
    ],
  },
  // 入魔阶段 (11-15)
  mindEater: {
    id: "mindEater",
    name: "噬心魔",
    maxHp: 66,
    intents: [
      { type: "attack", value: 13, text: "噬心 13" },
      { type: "status", status: "curse", stacks: 2, text: "心魔咒 2" },
      { type: "block", value: 10, text: "心壁 10" },
    ],
  },
  bloodGolem: {
    id: "bloodGolem",
    name: "血魔像",
    maxHp: 78,
    intents: [
      { type: "attack", value: 15, text: "血拳 15" },
      { type: "block", value: 14, text: "血壁 14" },
      { type: "status", status: "bleed", stacks: 2, text: "血沸 2" },
    ],
  },
  thunderDragon: {
    id: "thunderDragon",
    name: "雷蛟",
    maxHp: 62,
    intents: [
      { type: "attack", value: 12, text: "落雷 12" },
      { type: "status", status: "burn", stacks: 4, text: "雷火 4" },
      { type: "block", value: 8, text: "雷云护体 8" },
    ],
  },
  // 登真阶段 (16-20)
  doomPriest: {
    id: "doomPriest",
    name: "劫数祭司",
    maxHp: 90,
    intents: [
      { type: "attack", value: 16, text: "劫雷 16" },
      { type: "status", status: "curse", stacks: 4, text: "劫咒 4" },
      { type: "block", value: 15, text: "劫壁 15" },
    ],
  },
  asuraShade: {
    id: "asuraShade",
    name: "修罗影",
    maxHp: 100,
    intents: [
      { type: "attack", value: 18, text: "修罗斩 18" },
      { type: "block", value: 16, text: "修罗铠 16" },
      { type: "status", status: "bleed", stacks: 4, text: "修罗血涌 4" },
    ],
  },
  // 问武阶段 (21-25)
  trueDemon: {
    id: "trueDemon",
    name: "真魔",
    maxHp: 130,
    intents: [
      { type: "attack", value: 20, text: "魔临 20" },
      { type: "attack", value: 26, text: "灭道 26" },
      { type: "block", value: 20, text: "魔域 20" },
      { type: "status", status: "curse", stacks: 5, text: "万魔咒 5" },
    ],
  },
  // 真武专属 BOSS
  voidSovereign: {
    id: "voidSovereign",
    name: "虚渊主宰",
    maxHp: 220,
    intents: [
      { type: "attack", value: 18, text: "虚无之触 18" },
      { type: "attack", value: 28, text: "归墟 28" },
      { type: "block", value: 22, text: "渊壁 22" },
      { type: "status", status: "curse", stacks: 5, text: "虚渊咒 5" },
      { type: "status", status: "burn", stacks: 6, text: "虚无之炎 6" },
    ],
  },
};

export const relics = {
  poJunLing: { id: "poJunLing", name: "破军令", rarity: "legendary", text: "每场战斗开局格挡+22；物理卡牌伤害追加10点真伤。真武专属。", trueMartialOnly: true, implemented: true },
  nineSkyTribulation: { id: "nineSkyTribulation", name: "九天雷劫", rarity: "legendary", text: "天劫总伤 120；每场战斗开局敌方 3 层雷印。真武专属。", trueMartialOnly: true, implemented: true },
  asuraHeart: { id: "asuraHeart", name: "修罗心", rarity: "legendary", text: "每场战斗开局敌方获得 4 层流血；血魔吸血倍率翻倍。真武专属。", trueMartialOnly: true, implemented: true },
  venomScripture: { id: "venomScripture", name: "万毒真经", rarity: "legendary", text: "毒瘴每回合伤害翻倍，开局敌人中毒+8。真武专属。", trueMartialOnly: true, implemented: true },
  chaosTreasure: { id: "chaosTreasure", name: "混沌灵宝", rarity: "legendary", text: "开局敌方获得 1 层定力。真武专属。", trueMartialOnly: true, implemented: true },
  turtleShell: { id: "turtleShell", name: "玄龟甲", rarity: "legendary", text: "每场战斗开局格挡+30，反射伤害+25%。真武专属。", trueMartialOnly: true, implemented: true },
  bloodGourd: {
    id: "bloodGourd",
    name: "血葫芦",
    rarity: "rare",
    text: "每场战斗首次击败敌人时，回复 5 点生命。",
  },
  thunderSeal: {
    id: "thunderSeal",
    name: "雷部印",
    rarity: "rare",
    text: "每回合第一次造成卡牌伤害时，额外造成 4 点伤害。",
  },
  jadeRuyi: {
    id: "jadeRuyi",
    name: "玉如意",
    rarity: "epic",
    text: "每回合开始时，获得 1 点灵气。",
  },
  ghostLantern: {
    id: "ghostLantern",
    name: "引魂灯",
    rarity: "epic",
    text: "敌人死亡时，对所有敌人施加 2 层诅咒。",
  },
  chaosFragment: {
    id: "chaosFragment",
    name: "混沌碎片",
    rarity: "legendary",
    text: "每场战斗开始时，抽 2 张牌，获得 1 点能量。",
  },
  // 真武高收益高代价遗物
  bloodContract: {
    id: "bloodContract",
    name: "血契",
    rarity: "epic",
    text: "获得时最大生命降低20%；每场战斗胜利后回复15点生命。",
    trueMartialOnly: true,
    implemented: true,
  },
  cursedMirror: {
    id: "cursedMirror",
    name: "咒镜",
    rarity: "epic",
    text: "每回合开始时额外抽1张牌；每回合结束时获得2层诅咒。",
    trueMartialOnly: true,
    implemented: true,
  },
  berserkBrand: {
    id: "berserkBrand",
    name: "狂战烙印",
    rarity: "legendary",
    text: "真武专属。物理牌伤害翻倍；每次打出物理牌失去3点生命（最低保留1点）。",
    trueMartialOnly: true,
    implemented: true,
  },
  soulFurnace: {
    id: "soulFurnace",
    name: "魂炉",
    rarity: "epic",
    text: "每场战斗开局本场最大能量+1（临时），但同时失去8点生命（最低保留1点）。",
    trueMartialOnly: true,
    implemented: true,
  },
  hollowBlessing: {
    id: "hollowBlessing",
    name: "空虚赐福",
    rarity: "legendary",
    text: "每回合开始时获得2点能量，但格挡值减半并不可超过20。真武专属。",
    trueMartialOnly: true,
    implemented: false,
  },
  // V3.1: True Martial ascension relics
  infernoLotus: {
    id: "infernoLotus",
    name: "业火莲",
    rarity: "epic",
    text: "真武专属。你施加给敌人的灼烧层数提高50%；每场战斗开始时自身获得3层灼烧。",
    trueMartialOnly: true,
    implemented: true,
  },
  inverseScaleArmor: {
    id: "inverseScaleArmor",
    name: "逆鳞甲",
    rarity: "epic",
    text: "真武专属。每回合首次获得格挡时，额外获得50%；若回合结束仍有格挡，失去3点生命（最低保留1点）。",
    trueMartialOnly: true,
    implemented: true,
  },
  chaosBell: {
    id: "chaosBell",
    name: "乱魂铃",
    rarity: "epic",
    text: "真武专属。你施加控制状态时，额外造成4点伤害；目标同时获得1层定力。",
    trueMartialOnly: true,
    implemented: true,
  },
  // V3.3: physical / bleed / poison ascension relics
  bloodPrisonOath: {
    id: "bloodPrisonOath",
    name: "血狱誓",
    rarity: "epic",
    text: "真武专属。你施加给敌人的流血层数提高50%；每次施加流血时自身失去2点生命（最低保留1点）。",
    trueMartialOnly: true,
    implemented: true,
  },
  venomousCauldron: {
    id: "venomousCauldron",
    name: "万蛊盏",
    rarity: "epic",
    text: "真武专属。你施加给敌人的毒瘴层数提高50%；每次施加毒瘴时自身获得2层毒瘴。",
    trueMartialOnly: true,
    implemented: true,
  },
};

export const shopItems = {
  peachWine: {
    id: "peachWine",
    name: "蟠桃酒",
    price: 42,
    text: "最大生命 +8，并回复 8 点生命。",
    effects: [
      { type: "maxHp", value: 8 },
      { type: "heal", value: 8 },
    ],
  },
  spiritJade: {
    id: "spiritJade",
    name: "聚灵玉",
    price: 72,
    text: "最大能量 +1。本局最多购买一次。",
    once: true,
    effects: [{ type: "maxEnergy", value: 1 }],
  },
  greatSpiritJade: {
    id: "greatSpiritJade",
    name: "大聚灵玉",
    price: 148,
    text: "最大能量 +2。很贵，但能真正支撑三费爽牌。本局最多购买一次。",
    once: true,
    effects: [{ type: "maxEnergy", value: 2 }],
  },
  rareScroll: {
    id: "rareScroll",
    name: "灵箓残页",
    price: 48,
    text: "获得 1 张灵品以上卡牌。",
    effects: [{ type: "rareCard", value: 1 }],
  },
  doubleScroll: {
    id: "doubleScroll",
    name: "成套灵箓",
    price: 118,
    text: "获得 2 张灵品以上卡牌，适合快速补齐流派核心。",
    effects: [{ type: "rareCard", value: 2 }],
  },
  sleevePouch: {
    id: "sleevePouch",
    name: "袖里乾坤",
    price: 92,
    text: "手牌上限 +1，让保留手牌和高费牌更容易同时运转。本局最多购买一次。",
    once: true,
    effects: [{ type: "handLimit", value: 1 }],
  },
  sealBox: {
    id: "sealBox",
    name: "玄铁符匣",
    price: 58,
    text: "牌组上限 +5，并获得 20 金补贴。适合继续贪牌。",
    effects: [
      { type: "deckLimit", value: 5 },
      { type: "gold", value: 20 },
    ],
  },
  thunderTalisman: {
    id: "thunderTalisman",
    name: "雷部赦令",
    price: 96,
    text: "获得遗物雷部印。每回合第一次卡牌伤害额外造成 4 点。",
    once: true,
    effects: [{ type: "relic", value: "thunderSeal" }],
  },
  calmTea: {
    id: "calmTea",
    name: "清心茶",
    price: 35,
    text: "移除自身诅咒，并回复 6 点生命。",
    effects: [
      { type: "cleanse", status: "curse" },
      { type: "heal", value: 6 },
    ],
  },
  // 删牌系统
  purgeBasic: {
    id: "purgeBasic",
    name: "散功符",
    price: 40,
    text: "剔除一张基础牌（斩妖式/护身咒/黄符/调息），精简卡组。",
    effects: [{ type: "purgeCard", filter: "basic" }],
  },
  purgeAny: {
    id: "purgeAny",
    name: "斩念符",
    price: 75,
    text: "剔除任意一张可删除的牌，不可删除诅咒/业障牌。",
    effects: [{ type: "purgeCard", filter: "any" }],
  },
  // 真武专属商店物品
  purgeDoubleWithCurse: {
    id: "purgeDoubleWithCurse",
    name: "洗髓令",
    price: 90,
    text: "剔除两张牌，但获得一张业障（诅咒牌）。真武专属。",
    trueMartial: true,
    effects: [{ type: "purgeCard", filter: "twoWithCurse" }],
  },
  purgeWithBlood: {
    id: "purgeWithBlood",
    name: "血祭符",
    price: 30,
    text: "剔除一张牌，同时失去 12 点生命。真武专属。",
    trueMartial: true,
    effects: [{ type: "purgeCard", filter: "any" }, { type: "loseHpPlayer", value: 12 }],
  },
};


export const trueMartialDecks = {
  physical: ["strike","strike","heavySlash","chainBlade","traceCutter","readyStance","armorBreaker","killingIntent","furySlash","furySlash","warGodStrike","guard"],
  spell: ["foxFire","flameTalisman","thunderCharm","thunderCharm","attractThunder","thunderCall","thunderArmy","thunderBurst","guard","guard"],
  bleed: ["strike","strike","bloodNeedle","bloodNeedle","ghostNeedle","bloodNet","bloodSurge","bloodRecycle","bloodFang","bloodFang","guard"],
  poison: ["strike","strike","poisonPowder","poisonPowder","miasma","centipedeJar","poisonBurst","boneDust","venomFang","venomFang","guard"],
  control: ["strike","strike","strike","discordCharm","bindingRope","echoBell","stasisCharm","curseKill","guard","guard"],
  shell: ["guard","guard","strike","thornMail","thornMail","reflectArt","jiaoScale","shellTap","turtleCrush","strike"],
};
export const trueMartialRelics = { physical:"poJunLing", spell:"nineSkyTribulation", bleed:"asuraHeart", poison:"venomScripture", control:"chaosTreasure", shell:"turtleShell" };
export const startingDeck = [
  "strike",
  "strike",
  "strike",
  "strike",
  "strike",
  "guard",
  "guard",
  "guard",
  "guard",
  "meditate",
];
